- name: download wordpress
  get_url: 
    url: https://wordpress.org/latest.tar.gz
    dest: /wordpress.tar.gz

- name: Unpack wordpress
  unarchive: 
    src: /wordpress.tar.gz
    dest: /var/www/html
    remote_src: True

- name: copy new wordpress config 
  template: 
    src: templates/wp-config.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: download wp-cli to control via command line 
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: ./wp-cli.phar

- name: finish install with wp-cli
  command: php wp-cli.phar core install  --url="{{ wp_stireurl_var }}" --title="Weather Blog" --admin_user="lhorn" --admin_password="wordpress" --admin_email="someone@something.com" --allow-root --path="/var/www/html/wordpress"

- name: Make api call to metaWeather
  uri: 
    url: https://www.metaweather.com/api/location/2379574/
    method: GET
    return_content: yes
  register: jsonWeather

# Set varaibles for the weather attributes to use in the template for the post
- set_fact: temp="{{ jsonWeather.json.consolidated_weather[0].the_temp }}"
- set_fact: wstate="{{ jsonWeather.json.consolidated_weather[0].weather_state_name }}"
- set_fact: wabbr="{{ jsonWeather.json.consolidated_weather[0].weather_state_abbr }}"
- set_fact: date="{{ jsonWeather.json.consolidated_weather[0].applicable_date }}"


- name: Fill in the template for the post 
  template:
    src: templates/weather.j2
    dest: ./weather.txt

- name: Make post about weather 
  command: php wp-cli.phar post create ./weather.txt --path="/var/www/html/wordpress" --post_status=publish --post_title="Chicago Weather" --allow-root









