- name: install and configure wordpress
  get_url: 
    url: https://wordpress.org/latest.tar.gz
    dest: /wordpress.tar.gz

- name: Unpack the wordpress
  # file:
  #     path: /var/www/html
  #     state: directory
  unarchive: 
    src: /wordpress.tar.gz
    dest: /var/www/html
    remote_src: True
# - name: remove old config file 

# - name: copy new config file 
  