- name: Remove ips from hosts file  
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks: 
    - name: delete keys 
      ec2_key: 
        name: WordpressServer
        region: us-east-2
        state: absent
    - name: delete pem file 
      file: 
        path: WordpressServer.pem
        state: absent