- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  remote_user: ec2-user
  tasks: 
    - name: get VPC id
      ec2_vpc_net:
        name: WordpressVPC
        state: present
        cidr_block: 172.40.0.0/16
        region: us-east-2
        tags:
          module: ec2_vpc_net
      register: VPC 

    - name: remove subnet
      ec2_vpc_subnet:
        cidr: 172.40.0.0/24
        vpc_id: "{{ VPC.vpc.id }}"
        region: us-east-2
        resource_tags:
          Name: Wordpress Subnet
        state: absent

    - name: remove VPC 
      ec2_vpc_net:
        name: WordpressVPC
        state: absent
        cidr_block: 172.40.0.0/16
        region: us-east-2
        tags:
          module: ec2_vpc_net
